{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2024-03-28T19:50:51.003537Z",
     "start_time": "2024-03-28T19:50:46.464587Z"
    }
   },
   "outputs": [],
   "source": [
    "# # Import packages\n",
    "# import pandas as pd\n",
    "# import numpy as np\n",
    "# import os\n",
    "# import matplotlib.pyplot as plt\n",
    "# import seaborn as sns\n",
    "# import xgboost as xgb\n",
    "# \n",
    "# # Set options\n",
    "# pd.options.display.max_rows = 999\n",
    "# pd.options.display.max_columns = 999\n",
    "# \n",
    "# train_x_raw = pd.read_csv(\"../01-Data/X_train.csv\", low_memory = True, index_col=0)\n",
    "# train_y_raw = pd.read_csv(\"../01-Data/y_train.csv\", low_memory = True, index_col=0)\n",
    "# test_x_raw = pd.read_csv(\"../01-Data/X_test.csv\", low_memory=True, index_col=0)\n",
    "# \n",
    "# df_train = pd.DataFrame(train_x_raw)\n",
    "# df_test = pd.DataFrame(test_x_raw)\n",
    "# df_y = pd.DataFrame(train_y_raw)\n",
    "\n",
    "from EDA_script import *"
   ]
  },
  {
   "cell_type": "markdown",
   "source": [
    "# Model Run\n",
    "##  Random Forest with RandomizedSearchCV"
   ],
   "metadata": {
    "collapsed": false
   },
   "id": "c29cc48e8c64c78a"
  },
  {
   "cell_type": "code",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 3 folds for each of 10 candidates, totalling 30 fits\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=8, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=8, min_samples_split=6, n_estimators=202; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=8, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=8, min_samples_split=6, n_estimators=202; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=8, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=8, min_samples_split=6, n_estimators=202; total time=   0.0s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=6, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=8, min_samples_split=6, n_estimators=199; total time=   0.0s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=6, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=8, min_samples_split=6, n_estimators=199; total time=   0.0s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=6, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=8, min_samples_split=6, n_estimators=199; total time=   0.0s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=6, max_features=log2, min_samples_leaf=5, min_samples_split=3, n_estimators=443; total time=  16.7s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=6, max_features=log2, min_samples_leaf=5, min_samples_split=3, n_estimators=443; total time=  26.3s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=6, max_features=log2, min_samples_leaf=5, min_samples_split=3, n_estimators=443; total time=  23.6s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=9, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=413; total time=  29.0s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=9, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=413; total time=  24.8s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=9, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=413; total time=  20.7s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=7, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=463; total time=  36.1s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=7, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=463; total time=  36.8s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=7, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=463; total time=  34.4s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=4, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=5, min_samples_split=4, n_estimators=234; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=4, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=5, min_samples_split=4, n_estimators=234; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=4, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=5, min_samples_split=4, n_estimators=234; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=445; total time=  16.9s\n",
      "[CV] END bootstrap=True, criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=445; total time=  18.0s\n",
      "[CV] END bootstrap=True, criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=445; total time=  19.5s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=7, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=7, min_samples_split=9, n_estimators=134; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=7, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=7, min_samples_split=9, n_estimators=134; total time=   0.0s\n",
      "[CV] END bootstrap=True, criterion=entropy, max_depth=7, max_features=<scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85240>, min_samples_leaf=7, min_samples_split=9, n_estimators=134; total time=   0.0s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=7, max_features=log2, min_samples_leaf=8, min_samples_split=5, n_estimators=101; total time=   3.9s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=7, max_features=log2, min_samples_leaf=8, min_samples_split=5, n_estimators=101; total time=   3.8s\n",
      "[CV] END bootstrap=False, criterion=gini, max_depth=7, max_features=log2, min_samples_leaf=8, min_samples_split=5, n_estimators=101; total time=   3.6s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=9, max_features=log2, min_samples_leaf=4, min_samples_split=7, n_estimators=290; total time=  14.1s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=9, max_features=log2, min_samples_leaf=4, min_samples_split=7, n_estimators=290; total time=  13.8s\n",
      "[CV] END bootstrap=False, criterion=entropy, max_depth=9, max_features=log2, min_samples_leaf=4, min_samples_split=7, n_estimators=290; total time=  14.9s\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:547: FitFailedWarning: \n",
      "12 fits failed out of a total of 30.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB86320> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB873D0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB87A00> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB85BD0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB869B0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB879A0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB84C70> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB863E0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FB87730> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FD79C60> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FD79F00> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002201FD7A7A0> instead.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "C:\\Users\\amyoo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sklearn\\model_selection\\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [        nan         nan -1.11319005 -1.05185664 -1.02333457         nan\n",
      " -1.06935112         nan -1.08907372 -1.051653  ]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best parameters: {'bootstrap': False, 'criterion': 'gini', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 463}\n",
      "Best score: -1.0233345689493245\n",
      "Test Multiclass Logarithmic Loss: 1.006397410185323\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "import scipy.stats as stats\n",
    "from sklearn.metrics import log_loss\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "label_mapping = {-1: 0, 1: 1, 2: 2, 3: 3, 4: 4}\n",
    "df_y = df_y.replace(label_mapping)\n",
    "\n",
    "X_train, X_val, y_train, y_val = train_test_split(df_train, df_y.squeeze(), test_size=0.2, random_state=42)\n",
    "\n",
    "model = RandomForestClassifier(random_state=42)\n",
    "\n",
    "# Define the distribution of parameters\n",
    "param_distributions = {\n",
    "    'n_estimators': stats.randint(100, 500),\n",
    "    'max_depth': stats.randint(4, 10),\n",
    "    'min_samples_split': stats.randint(2, 11),\n",
    "    'min_samples_leaf': stats.randint(1, 11),\n",
    "    'bootstrap': [True, False],\n",
    "    'criterion': ['gini', 'entropy']\n",
    "}\n",
    "\n",
    "# RandomizedSearchCV / change n_iter, cv\n",
    "random_search = RandomizedSearchCV(estimator=model, param_distributions=param_distributions, n_iter=100, cv=3, scoring='neg_log_loss', random_state=42, verbose=2)\n",
    "random_search.fit(X_train, y_train)\n",
    "\n",
    "# Best parameters found\n",
    "print(\"Best parameters:\", random_search.best_params_)\n",
    "\n",
    "# Best score achieved\n",
    "print(\"Best score:\", random_search.best_score_)\n",
    "\n",
    "best_params = random_search.best_params_\n",
    "# RandomForestClassifier with the best parameters\n",
    "best_model = RandomForestClassifier(**best_params, random_state=42)\n",
    "\n",
    "# Fit the model\n",
    "best_model.fit(df_train, df_y.squeeze())  \n",
    "\n",
    "y_test_probs = best_model.predict_proba(X_val)  \n",
    "test_log_loss = log_loss(y_val, y_test_probs)  \n",
    "print(f\"Test Multiclass Logarithmic Loss: {test_log_loss}\")"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-03-28T19:58:59.354601Z",
     "start_time": "2024-03-28T19:50:56.487093Z"
    }
   },
   "id": "9a24b215b48afc4d",
   "execution_count": 2
  },
  {
   "cell_type": "markdown",
   "source": [],
   "metadata": {
    "collapsed": false
   },
   "id": "73377ae83e283639"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
